name: journey_tracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^3.26.0
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  path_provider: ^2.0.1
  percent_indicator: ^2.1.9+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.5


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/seasonJourney.json
  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Light.ttf
          - asset: fonts/Montserrat-LightItalic.ttf
            style: italic
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
